// Copyright (c) 2005-2011 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD/e, an XML Schema
// to C++ data binding compiler for embedded systems.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
//

#include <xsde/cxx/pre.hxx>

// Begin prologue.
//
//
// End prologue.

#include "wizard_schema.hxx"

namespace wizardxml
{
  // Wizard
  //

  const Wizard::Project_sequence& Wizard::
  Project () const
  {
    return this->Project_;
  }

  Wizard::Project_sequence& Wizard::
  Project ()
  {
    return this->Project_;
  }
}

#include <stdlib.h>
#include <new>

namespace wizardxml
{
  // Wizard
  //

  Wizard::
  Wizard ()
  {
  }

  Wizard::
  ~Wizard ()
  {
  }
}

// Begin epilogue.
//
//
// End epilogue.

#include <xsde/cxx/post.hxx>

