// Copyright (c) 2005-2011 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD/e, an XML Schema
// to C++ data binding compiler for embedded systems.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
//

// Begin prologue.
//
//
// End prologue.

#include "wizard_schema-sskel.hxx"

namespace wizardxml
{
  // Wizard_sskel
  //

  void Wizard_sskel::
  Project_serializer (::xml_schema::string_sskel& s)
  {
    this->Project_serializer_ = &s;
  }

  void Wizard_sskel::
  serializers (::xml_schema::string_sskel& Project)
  {
    this->Project_serializer_ = &Project;
  }

  Wizard_sskel::
  Wizard_sskel ()
  : Wizard_impl_ (0),
    Project_serializer_ (0)
  {
  }

  Wizard_sskel::
  Wizard_sskel (Wizard_sskel* impl, void*)
  : ::xsde::cxx::serializer::validating::complex_content (impl, 0),
    Wizard_impl_ (impl),
    Project_serializer_ (0)
  {
  }
}

#include <assert.h>

namespace wizardxml
{
  // Wizard_sskel
  //

  bool Wizard_sskel::
  Project_next ()
  {
    return this->Wizard_impl_ ? this->Wizard_impl_->Project_next () : false;
  }

  void Wizard_sskel::
  _reset ()
  {
    if (this->resetting_)
      return;

    typedef ::xsde::cxx::serializer::validating::complex_content base;
    base::_reset ();

    this->resetting_ = true;

    if (this->Project_serializer_)
      this->Project_serializer_->_reset ();

    this->resetting_ = false;
  }
}

namespace wizardxml
{
  // Element validation and serialization for Wizard_sskel.
  //
  void Wizard_sskel::
  _serialize_content ()
  {
    ::xsde::cxx::serializer::context& ctx = this->_context ();

    // Project
    //
    while (this->Project_next ())
    {
      const ::std::string& r = this->Project ();

      if (this->Project_serializer_)
      {
        this->Project_serializer_->pre (r);
        this->_start_element ("Project");
        this->Project_serializer_->_pre_impl (ctx);

        if (ctx.error_type ())
          return;

        this->Project_serializer_->_serialize_attributes ();

        if (ctx.error_type ())
          return;

        this->Project_serializer_->_serialize_content ();

        if (ctx.error_type ())
          return;

        this->Project_serializer_->_post_impl ();

        if (ctx.error_type ())
          return;

        this->_end_element ();
        this->Project_serializer_->post ();
      }
    }
  }
}

namespace wizardxml
{
}

// Begin epilogue.
//
//
// End epilogue.

