// Copyright (c) 2005-2011 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD/e, an XML Schema
// to C++ data binding compiler for embedded systems.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
//

// Begin prologue.
//
//
// End prologue.

#include "installation_schema-pimpl.hxx"

#include <xsde/cxx/parser/validating/string-common.hxx>

namespace installationxml
{
  // Installation_pimpl
  //

  void Installation_pimpl::
  pre ()
  {
    this->Installation_pimpl_state_.Installation_ = ::installationxml::Installation ();
  }

  void Installation_pimpl::
  Version (const ::std::string& x)
  {
    this->Installation_pimpl_state_.Installation_.Version (x);
  }

  void Installation_pimpl::
  Python (const ::std::string& x)
  {
    this->Installation_pimpl_state_.Installation_.Python (x);
  }

  void Installation_pimpl::
  Toolchain (const ::std::string& x)
  {
    this->Installation_pimpl_state_.Installation_.Toolchain (x);
  }

  void Installation_pimpl::
  SDK (const ::std::string& x)
  {
    this->Installation_pimpl_state_.Installation_.SDK (x);
  }

  ::installationxml::Installation Installation_pimpl::
  post_Installation ()
  {
    return this->Installation_pimpl_state_.Installation_;
  }
}

namespace installationxml
{
  // Installation_paggr
  //

  Installation_paggr::
  Installation_paggr ()
  {
    this->Installation_p_.parsers (this->string_p_,
                                   this->string_p_,
                                   this->string_p_,
                                   this->string_p_);
  }

  const char* Installation_paggr::
  root_name ()
  {
    return "Installation";
  }

  const char* Installation_paggr::
  root_namespace ()
  {
    return "";
  }
}

// Begin epilogue.
//
//
// End epilogue.

