// Copyright (c) 2005-2011 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD/e, an XML Schema
// to C++ data binding compiler for embedded systems.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
//

// Begin prologue.
//
//
// End prologue.

#include "installation_schema-simpl.hxx"

#include <xsde/cxx/serializer/validating/string-common.hxx>

namespace installationxml
{
  // Installation_simpl
  //

  void Installation_simpl::
  pre (const ::installationxml::Installation& x)
  {
    this->Installation_simpl_state_.Installation_ = &x;
  }

  ::std::string Installation_simpl::
  Version ()
  {
    return this->Installation_simpl_state_.Installation_->Version ();
  }

  ::std::string Installation_simpl::
  Python ()
  {
    return this->Installation_simpl_state_.Installation_->Python ();
  }

  ::std::string Installation_simpl::
  Toolchain ()
  {
    return this->Installation_simpl_state_.Installation_->Toolchain ();
  }

  ::std::string Installation_simpl::
  SDK ()
  {
    return this->Installation_simpl_state_.Installation_->SDK ();
  }
}

namespace installationxml
{
  // Installation_saggr
  //

  Installation_saggr::
  Installation_saggr ()
  {
    this->Installation_s_.serializers (this->string_s_,
                                       this->string_s_,
                                       this->string_s_,
                                       this->string_s_);
  }

  const char* Installation_saggr::
  root_name ()
  {
    return "Installation";
  }

  const char* Installation_saggr::
  root_namespace ()
  {
    return "";
  }
}

// Begin epilogue.
//
//
// End epilogue.

