// Copyright (c) 2005-2011 Code Synthesis Tools CC
//
// This program was generated by CodeSynthesis XSD/e, an XML Schema
// to C++ data binding compiler for embedded systems.
//
// This program is free software; you can redistribute it and/or modify
// it under the terms of the GNU General Public License version 2 as
// published by the Free Software Foundation.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program; if not, write to the Free Software
// Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
//
//

#ifndef W__WORKSPACE_EG_SRC_SCHEMA_SCHEMA_PIMPL_HXX
#define W__WORKSPACE_EG_SRC_SCHEMA_SCHEMA_PIMPL_HXX

#include <xsde/cxx/pre.hxx>

// Begin prologue.
//
//
// End prologue.

#ifndef XSDE_OMIT_PAGGR
#  define XSDE_OMIT_PAGGR
#  define W__WORKSPACE_EG_SRC_SCHEMA_SCHEMA_PIMPL_HXX_CLEAR_OMIT_PAGGR
#endif

#include "schema-pskel.hxx"

#include <xsde/cxx/stack.hxx>

class name_pimpl: public name_pskel
{
  public:
  name_pimpl ();

  virtual void
  pre ();

  virtual ::name
  post_name ();

  public:
  ::xml_schema::string_pimpl base_impl_;

  public:
  struct name_pimpl_state
  {
    ::name name_;
  };

  name_pimpl_state name_pimpl_state_;
};

class Config_pimpl: public Config_pskel
{
  public:
  virtual void
  pre ();

  // Elements.
  //
  virtual void
  name (const ::name&);

  virtual void
  file (bool);

  virtual ::Config
  post_Config ();

  public:
  struct Config_pimpl_state
  {
    ::Config Config_;
  };

  Config_pimpl_state Config_pimpl_state_;
};

class eg_pimpl: public eg_pskel
{
  public:
  eg_pimpl (bool = false);

  ~eg_pimpl ();

  virtual void
  _reset ();

  virtual void
  pre ();

  // Elements.
  //
  virtual void
  host (const ::std::string&);

  virtual void
  folder (const ::std::string&);

  virtual void
  stuff (const ::Config&);

  virtual ::eg*
  post_eg ();

  public:
  void
  pre_impl (::eg*);

  public:
  struct eg_pimpl_state
  {
    ::eg* eg_;
  };

  eg_pimpl_state eg_pimpl_state_;
  bool eg_pimpl_base_;
};

#ifdef W__WORKSPACE_EG_SRC_SCHEMA_SCHEMA_PIMPL_HXX_CLEAR_OMIT_PAGGR
#  undef XSDE_OMIT_PAGGR
#endif

#ifndef XSDE_OMIT_PAGGR

// Parser aggregate for the eg element.
//
class eg_paggr
{
  public:
  eg_paggr ();

  void
  pre ()
  {
    this->eg_p_.pre ();
  }

  ::eg*
  post ()
  {
    return this->eg_p_.post_eg ();
  }

  ::eg_pimpl&
  root_parser ()
  {
    return this->eg_p_;
  }

  static const char*
  root_name ();

  static const char*
  root_namespace ();

  void
  reset ()
  {
    this->eg_p_._reset ();
  }

  public:
  ::Config_pimpl Config_p_;
  ::name_pimpl name_p_;
  ::eg_pimpl eg_p_;
  ::xml_schema::string_pimpl string_p_;
  ::xml_schema::boolean_pimpl boolean_p_;
};

#endif // XSDE_OMIT_PAGGR

// Begin epilogue.
//
//
// End epilogue.

#include <xsde/cxx/post.hxx>

#endif // W__WORKSPACE_EG_SRC_SCHEMA_SCHEMA_PIMPL_HXX
